accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),

]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),

]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # When Django examines a requested URL, this pattern
    # will match any URL that has the base URL followed by topics.

    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry.
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # Page for editing an entry.
    path('edit_entry/<int:entry_id/', views.edit_entry, name='edit_entry'),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models

"""
A model tells Django how to work with the data that will be stored in the app.
A model is a class, it has attributes and methods。
"""
# Create your models here.

class Topic(models.Model):
    """A topic the user is learning about."""
    """Inherits from Model - a parent class included in Django 
    that defines a model's basic functionality."""
    text = models.CharField(max_length=200)
    # use CharField when want to stor a small amount of text.
    data_added = models.DateTimeField(auto_now_add=True)
    # We pass the argument auto_now_add=True, which tells Django to
    # automatically set this attribute to the current date and time
    # whenever the user creates a new topic.

    def __str__(self):
        """Return a string representation of the model."""
        return self.text
        # Here we’ve written a __str__() method that returns
        # the value assigned to the text attribute.


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    # ForeignKey is a reference to another record in the database.
    # This is the code that connects each entry to a specific topic.

    # on_delete=models.CASCADE argument tells Django that when a
    # topic is deleted, all the entries associated with that topic
    # should be deleted as well.
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        # The Meta class telling Django which model to base the form on
        # and which fields to include in the form.
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        # The empty string in the labels dictionary tells Django not
        # to generate a label for the text field.

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/views.py
from django.shortcuts import render, redirect

from .models import Topic, Entry
from .forms import TopicForm, EntryForm
# Create your views here.

def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')


def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('data_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Show a single topic and all its entries.
    The function accepts the value captured by the expression /<int:topic_id>/
    and assigns it to topic_id.
    """
    topic = Topic.objects.get(id=topic_id)   # retrieve the topic
    entries = topic.entry_set.order_by('-date_added')
    # sign"-" sorts the results in reverse order,
    # display the most recent entries first.
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/demo/HELLO.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gigigi</title>
    <script src="js/count.js"></script>
</head>
<body>
    <h1>0</h1>
    <button>Count</button>

    <form>
        <input autofocus id="name" placeholder="Name" type="text">
        <input type="submit">
    </form>


    <h2 id="hello">Color</h2>
    <button class="color-button" data-color="red">Red</button>
    <button class="color-button" data-color="blue">Blue</button>
    <button class="color-button" data-color="green">Green</button>


    <select>
        <option value="black">Black</option>
        <option value="blue">Blue</option>
        <option value="red">Red</option>
        <option value="green">Green</option>
    </select>
</body>
</html>

learning_logs/templates/demo/counter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Counter</title>
    <script>

        document.addEventListener('DOMContentLoaded', () => {

            let counter = 0;

            document.querySelector('#increase').onclick = () => {
                counter++;
                document.querySelector('h1').innerHTML = counter;
            }

            document.querySelector('#decrease').onclick = () => {
                counter--;
                document.querySelector('h1').innerHTML = counter;
            }
        })
    </script>
</head>
<body>
    <h1>0</h1>
    <button id="increase">+</button>
    <button id="decrease">-</button>
</body>
</html>

learning_logs/templates/demo/currency.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Currency Exchange</title>
    <script>
        document.addEventListener('DOMContentLoaded', function () {

            document.querySelector('form').onsubmit = function () {

                fetch('https://api.exchangeratesapi.io/latest?base=USD')
                .then(response => response.json())
                .then(data => {
                    const currency = document.querySelector('#currency').value.toUpperCase();
                    const rate = data.rates[currency];
                    if (rate !== undefined) {
                        document.querySelector('#result').innerHTML = `1 USD is eqyal to ${rate.toFixed(3)} ${currency}.`;
                    } else {
                        document.querySelector('#result').innerHTML = 'Invalid currency.';

                    }

                })
                  .catch(error => {
                    console.log('Error:', error);
                })
                return false
            }


        })
    </script>
</head>
<body>
    <form>
        <input id="currency" placeholder="Currency" type="text">
        <input type="submit" value="Convert">
    </form>
    <div id="result">

    </div>
</body>
</html>

learning_logs/templates/demo/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>中华典籍</title>
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
    <header>
        <h1>中华典籍</h1>
    </header>
    <main>
        <div class="chat-container">
            <div class="chat-history" id="chat-history">
                <!-- 聊天记录将显示在这里 -->
            </div>
            <div class="chat-input">
                <input type="text" id="user-input" placeholder="请输入您的问题">
                <button id="send-btn">发送</button>
            </div>
        </div>
    </main>
    <script src="js/main.js"></script>
</body>
</html>

learning_logs/templates/demo/single.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Single Page</title>
    <style>
        div{
            display: none;
        }
    </style>
    <script>

        function showPage(page) {
            document.querySelectorAll('div').forEach(div => {
                div.style.display = 'none';
            })
            document.querySelector(`#${page}`).style.display = 'block';
        }

        document.addEventListener('DOMContentLoaded', function () {
            document.querySelectorAll('button').forEach(button => {
                button.onclick = function () {
                    showPage(this.dataset.page);
                }
            })
        })
    </script>
</head>
<body>
    <button data-page="page1">Page 1</button>
    <button data-page="page2">Page 2</button>
    <button data-page="page3">Page 3</button>
    <div id="page1">
        <h1>THis is page 1.</h1>
    </div>
    <div id="page2">
        <h1>THis is page 2.</h1>
    </div>
    <div id="page3">
        <h1>THis is page 3.</h1>
    </div>
</body>
</html>

learning_logs/templates/demo/tasks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks</title>
    <script>
        document.addEventListener('DOMContentLoaded', function () {

            // By default, submit button is disabled
            document.querySelector('#submit').disabled = true;

            document.querySelector('#task').onkeyup = () => {
                if (document.querySelector('#task').value.length > 0) {
                    document.querySelector('#submit').disabled = false;
                } else {
                    document.querySelector('#submit').disabled = true;
                }
            }

            document.querySelector('form').onsubmit = () => {
                const task = document.querySelector('#task').value;
                console.log(task);

                const li = document.createElement('li');
                li.innerHTML = task;

                document.querySelector('#tasks').append(li);

                document.querySelector('#task').value = '';
                document.querySelector('#submit').disabled = true;
                // Stop form from submitting
                return false;
            }
        })
    </script>
</head>
<body>
    <h1>Tasks</h1>
    <ul id="tasks">

    </ul>
    <form>
        <input id="task" placeholder="New Task" type="text">
        <input id="submit" type="submit">
    </form>
</body>
</html>

learning_logs/templates/learning_logs/base.html
<p>
  <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
  <!-- generates a URL matching the URL pattern defined in learning_logs/urls.py with the name 'index'. -->
  <a href="{% url 'learning_logs:topics' %}">Topics</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }}.
  {% else %}
    <a href="{% url 'accounts:register' %}">Register</a> -
    <a href="{% url 'accounts:login' %}">Log in</a>
  {% endif %}
</p>


{% block content %}{% endblock content %}

{% if user.is_authenticated %}]
  <hr />
  <form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <button name="submit">Log out</button>
  </form>
{% endif %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_div }}
      <button name="submit">Save changes</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
  <p>Learning Log helps you keep track of your learning, for any topic you're interested in.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_div }}
      <button name='submit'>Add entry</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Add a new topic</p>

  <form action="{% url 'learning_logs:new_topic' %}" method="post">
      {% csrf_token %}
      {{ form.as_div }}
      <button name="submit">Add topic</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>Topic: {{ topic.text }}</p>

  <p>Entries:</p>
    <p>
      <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>

  <ul>
      {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{%  url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
            </p>
        </li>
      {% empty %}
        <li>There are no entries for this topic yet.</li>
      {% endfor %}
  </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>Topics</p>
  <ul>
      {% for topic in topics %}
        <li>
          <a href="{% url 'learning_logs:topic' topic.id %}">
              {{ topic.text }}</a>
        </li>
      {% empty %}
        <li>No topics have been added yet.</li>
      {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}